version: '3'
services:
  postgres:
    restart: always
    image: postgres:10.6
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - setup.env
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=testdb
  app:
    restart: always
    env_file:
      - setup.env
    environment:
      - WEBSITE_UPLOADS=flask_rest_psql_docker/website/uploads
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - postgres
    entrypoint: ["gunicorn", "-b", "0.0.0.0:5000", "wsgi:app"]
