"""empty message

Revision ID: 3f2fcedfda55
Revises: 
Create Date: 2019-02-08 14:56:19.977557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f2fcedfda55'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first', sa.String(length=80), nullable=True),
    sa.Column('last', sa.String(length=80), nullable=True),
    sa.Column('school', sa.String(length=80), nullable=True),
    sa.Column('job', sa.String(length=80), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('people')
    # ### end Alembic commands ###
